### ISSUE TITLE
Img-alt-text Needs to check more than just pages

### ISSUE THREAD

**Issue by danverde** [byuitechops/check-alt-property#2]
Maybe use framework from blueprint-lock-items to get all HTML?

**Comment by maeashley** [comment]
Waiting to see if this module will be a grandchild or not

**Comment by maeashley** [comment]
Fixed this using a universal grandchild. See [this commit](https://github.com/byuitechops/action-series-master/commit/c33c394e55357734d7c689314c9709e9af5928cc) for details.
